# Generated by Django 4.2.3 on 2023-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('website', models.URLField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Video',
        ),
    ]
