# Generated by Django 4.2.3 on 2023-07-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice_app', '0002_streamplatform_rename_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='apipractice_app.streamplatform'),
            preserve_default=False,
        ),
    ]
