# Generated by Django 4.2.3 on 2023-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice_app', '0004_alter_video_platform_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
