# Generated by Django 4.2.3 on 2023-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipractice_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
